package applicationaero;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julien.mannechez
 */
public class Membres extends javax.swing.JFrame {
private Menu fen;
    /**
     * Creates new form Membres
     */
    
    bdd.Connecter conn = new bdd.Connecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model=new DefaultTableModel();
        
    public Membres() {
        
        this.setVisible(true);
        
        initComponents();
        
model.addColumn("Num_Membre");     
model.addColumn("Nom");      
model.addColumn("Prenom");  
model.addColumn("Portable");   
model.addColumn("Profession");   
model.addColumn("Code_Postal");   
model.addColumn("Ville");  


 
try{
    stm=conn.obtenirconnexion().createStatement();
    ResultSet Rs=stm.executeQuery("Select * from membres");
    while(Rs.next()){
        model.addRow(new Object[]{Rs.getString("Num_Membre"),Rs.getString("Nom"),Rs.getString("Prenom"),
                Rs.getString("Portable"),Rs.getString("Profession"),
                Rs.getString("Code_Postal"),Rs.getString("Ville"),});
        }
}
catch(Exception e)
{
    System.err.println(e);
}

tble.setModel(model);

}

        
            
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        comm = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        txtre = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNUM_MEMBRE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNUM_QUALIF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtadresse = new javax.swing.JTextField();
        txtNUM_CIVILITE = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtLIEU_NAISSANCE = new javax.swing.JTextField();
        txtDATE_SEP = new javax.swing.JTextField();
        txtcp = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtville = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtdatenaiss = new javax.swing.JTextField();
        txtCARTE_FEDERALE = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        txtportable = new javax.swing.JTextField();
        txtprof = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtDATE_VM = new javax.swing.JTextField();
        txtVALIDITE_VM = new javax.swing.JTextField();
        txtVALIDITE_SEP = new javax.swing.JTextField();
        txtDATE_ATTESTATION = new javax.swing.JTextField();
        txtNUM_BADGE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsolde = new javax.swing.JTextField();
        txtCommentaires = new javax.swing.JTextField();
        txtMEMBRE_ACTIF = new javax.swing.JTextField();
        txtMEMBRE_INSCRIT = new javax.swing.JTextField();
        txtNUMERO_PPLA = new javax.swing.JTextField();
        txtDATE_ENTREE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        comm.setColumns(20);
        comm.setRows(5);
        jScrollPane1.setViewportView(comm);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("GentiumAlt", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GERER LES MEMBRES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tble);

        jButton4.setText("Actualiser");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("AJouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Modifier");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton6.setText("Rechercher");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtre, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtre))
                .addGap(34, 34, 34))
        );

        jLabel8.setText("Profession");

        jLabel9.setText("Portable");

        jLabel10.setText("Mail");

        jLabel11.setText("Date naissance ");

        jLabel12.setText("Commentaires");

        jLabel31.setText("LIEU_NAISSANCE");

        jLabel34.setText("CARTE_FEDERALE");

        jLabel35.setText("DATE_SEP");

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });

        jLabel18.setText("SOLDE_COMPTE");

        jLabel14.setText("VALIDITE_SEP");

        jLabel15.setText("NUM_BADGE");

        jLabel17.setText("VALIDITE_VM");

        jLabel13.setText("DATE_VM");

        jLabel19.setText("DATE_ATTESTATION");

        jLabel26.setText("NUMERO_PPLA");

        jLabel27.setText("DATE_ENTREE");

        jLabel28.setText("MEMBRE_ACTIF");

        jLabel29.setText("MEMBRE_INSCRIT");

        txtDATE_VM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDATE_VMActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom");

        jLabel3.setText("Prenom");

        jLabel4.setText("Adresse ");

        jLabel5.setText("Tel");

        jLabel23.setText("NUM_MEMBRE");

        jLabel6.setText("CodePostal");

        jLabel25.setText("NUM_CIVILITE");

        jLabel7.setText("Ville");

        jLabel30.setText("NUM_QUALIF");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel35)
                    .addComponent(jLabel30)
                    .addComponent(jLabel23))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtprof)
                    .addComponent(txtportable)
                    .addComponent(txttel)
                    .addComponent(txtprenom)
                    .addComponent(txtnom)
                    .addComponent(txtDATE_VM)
                    .addComponent(txtVALIDITE_VM)
                    .addComponent(txtVALIDITE_SEP)
                    .addComponent(txtNUM_QUALIF)
                    .addComponent(txtDATE_SEP)
                    .addComponent(txtNUM_MEMBRE)
                    .addComponent(txtNUMERO_PPLA)
                    .addComponent(txtNUM_BADGE)
                    .addComponent(txtDATE_ENTREE, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel25)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(txtville, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtdatenaiss, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLIEU_NAISSANCE, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCARTE_FEDERALE)
                    .addComponent(txtMEMBRE_ACTIF)
                    .addComponent(txtNUM_CIVILITE)
                    .addComponent(txtMEMBRE_INSCRIT)
                    .addComponent(txtsolde)
                    .addComponent(txtDATE_ATTESTATION)
                    .addComponent(txtadresse)
                    .addComponent(txtCommentaires))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtadresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(469, 469, 469))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel23))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(txtportable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtdatenaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(txtprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31)
                                            .addComponent(txtLIEU_NAISSANCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtDATE_VM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel10)
                                            .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtVALIDITE_VM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel19)
                                            .addComponent(txtDATE_ATTESTATION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtVALIDITE_SEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel28)
                                            .addComponent(txtMEMBRE_ACTIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtNUM_BADGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel29)
                                            .addComponent(txtMEMBRE_INSCRIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtNUMERO_PPLA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel25)
                                            .addComponent(txtNUM_CIVILITE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDATE_ENTREE, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel27)
                                                .addComponent(jLabel34)
                                                .addComponent(txtCARTE_FEDERALE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(txtcp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(txtville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNUM_MEMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtsolde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNUM_QUALIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel12)
                            .addComponent(txtCommentaires, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(txtDATE_SEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel24))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void deplace(int i){
    try{
        txtNUM_MEMBRE.setText(model.getValueAt(i,0).toString());
        txtNUM_QUALIF.setText(model.getValueAt(i,1).toString());
        txtNUM_CIVILITE.setText(model.getValueAt(i,2).toString());
        txtnom.setText(model.getValueAt(i,3).toString());
        txtprenom.setText(model.getValueAt(i,4).toString());
        txtadresse.setText(model.getValueAt(i,5).toString());
        txtcp.setText(model.getValueAt(i,6).toString());
        txtville.setText(model.getValueAt(i,7).toString());
        txttel.setText(model.getValueAt(i,8).toString());
        txtportable.setText(model.getValueAt(i,9).toString());
        txtmail.setText(model.getValueAt(i,10).toString());
        txtCommentaires.setText(model.getValueAt(i,11).toString());
        txtDATE_VM.setText(model.getValueAt(i,12).toString());
        txtVALIDITE_VM.setText(model.getValueAt(i,13).toString());
        txtDATE_SEP.setText(model.getValueAt(i,14).toString());
        txtVALIDITE_SEP.setText(model.getValueAt(i,15).toString());
        txtNUM_BADGE.setText(model.getValueAt(i,16).toString());
        txtportable.setText(model.getValueAt(i,17).toString());
        txtdatenaiss.setText(model.getValueAt(i,18).toString());
        txtLIEU_NAISSANCE.setText(model.getValueAt(i,19).toString());
        txtCARTE_FEDERALE.setText(model.getValueAt(i,20).toString());
        txtDATE_ATTESTATION.setText(model.getValueAt(i,21).toString());
        txtDATE_ENTREE.setText(model.getValueAt(i,22).toString());
        txtMEMBRE_ACTIF.setText(model.getValueAt(i,23).toString());
        txtMEMBRE_INSCRIT.setText(model.getValueAt(i,24).toString());
        txtsolde.setText(model.getValueAt(i,25).toString());

       

    }
    catch(Exception e){
        System.err.println(e);
        JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());
    }
}


private void afficher(){
try{
    
        model.setRowCount(0);
    stm=conn.obtenirconnexion().createStatement();
    ResultSet Rs=stm.executeQuery("Select * from membres");
    while(Rs.next()){
        model.addRow(new Object[]{Rs.getString("Num_Membre"),Rs.getString("Nom"),Rs.getString("Prenom"),
                Rs.getString("Portable"),Rs.getString("Profession"),
                Rs.getString("Code_Postal"),Rs.getString("Ville")});
        }
}
catch(Exception e)
{
    System.err.println(e);
}

tble.setModel(model);


}        
        
        
        
        
        
    
    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        fen = new Menu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: SUPPRIMER 
try {
    if(JOptionPane.showConfirmDialog(null,"êtes vous sur de vouloir supprimer ce membre "
    ,"supprimer membre",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
        
    if(txtNUM_MEMBRE.getText().length() != 0) {
        stm.executeUpdate("Delete From membres where Num_Membre="+txtNUM_MEMBRE.getText()); afficher();
        
    }
    else {
        JOptionPane.showMessageDialog(null,"veuillez remplire le champ NUM_MEMBRE !! "); 
        
    }
}   
catch(Exception e) 
{
    JOptionPane.showMessageDialog(null,"erreur suppr \n"+e.getMessage());
            
}    
      
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
        // TODO add your handling code here: Affiche dans le formulaire
        
        String id;
        id = (String.valueOf(tble.getValueAt(tble.getSelectedRow(), 0)));
        try {
            Rs=stm.executeQuery("Select * from membres Where Num_Membre='"+id+"'");

            Rs.next();
            txtNUM_MEMBRE.setText(Rs.getString(1));
            txtNUM_QUALIF.setText(Rs.getString(2));
            txtNUM_CIVILITE.setText(Rs.getString(3));
            txtnom.setText(Rs.getString(4));
            txtprenom.setText(Rs.getString(5));
            txtadresse.setText(Rs.getString(6));  
            txtcp.setText(Rs.getString(7));
            txtville.setText(Rs.getString(8));
            txttel.setText(Rs.getString(9));
            txtportable.setText(Rs.getString(10));
            txtmail.setText(Rs.getString(11));
            txtCommentaires.setText(Rs.getString(12));
            txtDATE_VM.setText(Rs.getString(13));
            txtVALIDITE_VM.setText(Rs.getString(14));  
            txtDATE_SEP.setText(Rs.getString(15));
            txtVALIDITE_SEP.setText(Rs.getString(16));
            txtNUM_BADGE.setText(Rs.getString(17));
            txtprof.setText(Rs.getString(18));  
            txtdatenaiss.setText(Rs.getString(19));
            txtLIEU_NAISSANCE.setText(Rs.getString(20));
            txtCARTE_FEDERALE.setText(Rs.getString(21));
            txtDATE_ATTESTATION.setText(Rs.getString(22));  
            txtDATE_ENTREE.setText(Rs.getString(23));
            txtMEMBRE_ACTIF.setText(Rs.getString(24));
            txtMEMBRE_INSCRIT.setText(Rs.getString(25)); 
            txtsolde.setText(Rs.getString(26)); 
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"erreur de deplacement "+ex.getLocalizedMessage());
        }

    }//GEN-LAST:event_tbleMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: AJOUT MEMBRE
        String Num_Membre=txtNUM_MEMBRE.getText();
        String Num_Qualif=txtNUM_QUALIF.getText();
        String Num_Civilite=txtNUM_CIVILITE.getText();
        String Nom=txtnom.getText();
        String Prenom=txtprenom.getText();  
        String Adresse=txtadresse.getText();
        String Code_Postal=txtcp.getText();
        String Ville=txtville.getText();
        String Telephone=txttel.getText();
        String Portable=txtportable.getText();
        String Email=txtmail.getText();
        String Commentaire=txtCommentaires.getText();
        String Date_VM=txtDATE_VM.getText();
        String Validite_VM=txtVALIDITE_VM.getText();
        String Date_SEP=txtDATE_SEP.getText();
        String Validite_SEP=txtVALIDITE_SEP.getText();
        String Num_Badge=txtNUM_BADGE.getText();
        String Profession=txtprof.getText();
        String Date_Naissance=txtdatenaiss.getText();        
        String Lieu_Naissance=txtLIEU_NAISSANCE.getText();
        String Carte_Federal=txtCARTE_FEDERALE.getText();
        String Date_Attestation=txtDATE_ATTESTATION.getText();
        String Date_Entree=txtDATE_ENTREE.getText();
        String Menbre_Actif=txtMEMBRE_ACTIF.getText();
        String Menbre_Inscrit=txtMEMBRE_INSCRIT.getText();
        String Solde_Compte=txtsolde.getText();

        
        String requete="insert into membres(Num_Membre,Num_Qualif,Num_Civilite,Nom,Prenom,Adresse,Code_Postal,Ville,Telephone,Portable,Email,Commentaire,Date_VM,Validite_VM,Date_SEP,Validite_SEP,Num_Badge,Profession,Date_Naissance,Lieu_Naissance,Carte_Federal,Date_Attestation,Date_Entree,Menbre_Actif,Menbre_Inscrit,Solde_Compte) VALUES ('"+Num_Membre+"','"+Num_Qualif+"','"+Num_Civilite+"','"+Nom+"','"+Prenom+"','"+Adresse+"','"+Code_Postal+"','"+Ville+"','"+Telephone+"','"+Portable+"','"+Email+"','"+Commentaire+"','"+Date_VM+"','"+Validite_VM+"','"+Date_SEP+"','"+Validite_SEP+"','"+Num_Badge+"','"+Profession+"','"+Date_Naissance+"','"+Lieu_Naissance+"','"+Carte_Federal+"','"+Date_Attestation+"','"+Date_Entree+"','"+Menbre_Actif+"','"+Menbre_Inscrit+"','"+Solde_Compte+"')";
                 try {
                     
                     stm.executeUpdate(requete);
                     JOptionPane.showMessageDialog(null,"Membres ajouté");
                     txtNUM_MEMBRE.setText("");
                     txtnom.setText("");
                     txtprenom.setText("");
                     txtportable.setText("");
                     txtprof.setText("");
                     txtcp.setText("");
                     txtville.setText("");
                     afficher();
                     
                     
                 }
                 catch(Exception ex){
                     JOptionPane.showMessageDialog(null,ex.getMessage());
                 }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
afficher();     

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtDATE_VMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDATE_VMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDATE_VMActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here: MODIFIER MEMBRE


try{
    if(JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",
            JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
        
        stm.executeUpdate("UPDATE membres SET Num_Membre='"+txtNUM_MEMBRE.getText()+"',Num_Qualif='"+txtNUM_QUALIF.getText()+
                "',Num_Civilite='"+txtNUM_CIVILITE.getText()+"',Nom='"+txtnom.getText()+
                        "',Prenom='"+txtprenom.getText()+"',Adresse='"+txtadresse.getText()+
                                "',Code_Postal='"+txtcp.getText()+"',Ville='"+txtville.getText()+
                                        "',Telephone='"+txttel.getText()+"',Portable='"+txtportable.getText()+
                                                "',Email='"+txtmail.getText()+"',Commentaire='"+txtCommentaires.getText()+"',Date_VM='"+txtDATE_VM.getText()+
                                                        "',Validite_VM='"+txtVALIDITE_VM.getText()+"',Date_SEP='"+txtDATE_SEP.getText()+"',Validite_SEP='"+txtVALIDITE_SEP.getText()+
                        "',Num_Badge='"+txtNUM_BADGE.getText()+"',Profession='"+txtprof.getText()+"',Date_Naissance='"+txtdatenaiss.getText()+
                                "',Lieu_Naissance='"+txtLIEU_NAISSANCE.getText()+"',Carte_Federal='"+txtCARTE_FEDERALE.getText()+"',Date_Attestation='"+txtDATE_ATTESTATION.getText()+
                                "',Date_Entree='"+txtDATE_ENTREE.getText()+"',Menbre_Actif='"+txtMEMBRE_ACTIF.getText()+"',Menbre_Inscrit='"+txtMEMBRE_INSCRIT.getText()+"',Solde_Compte='"+txtsolde.getText()+
                                "' WHERE Num_Membre= "+txtNUM_MEMBRE.getText());
        afficher();
               
    }
}     
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"erreur modif ! "+e.getMessage());
    System.err.println(e);
}
        
        

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here: RECHERCHE MEMBRE PAR NUM
        
try {
    model.setRowCount(0); // ON VIDE LA LISTES DES MEMBRES
    
    {
        Rs = stm.executeQuery("Select * from membres WHERE Num_Membre= '"+txtre.getText()+"'");
        
    }while (Rs.next()){
        Object [] membres ={Rs.getString(1),Rs.getString(2),Rs.getString(3),Rs.getString(4),Rs.getString(5),Rs.getString(6),
        Rs.getString(7),Rs.getString(8),Rs.getString(9),Rs.getString(10),Rs.getString(11),Rs.getString(12),Rs.getString(13),Rs.getString(14),
        Rs.getString(15),Rs.getString(16),Rs.getString(16),Rs.getString(17),Rs.getString(18),Rs.getString(19)};
   model.addRow(membres);     
    }   if (model.getRowCount () == 0){
        JOptionPane.showMessageDialog(null,"Il n'y a aucun membres");
    }
    else{ int i=0;
    deplace(i);
    
    }
}
catch(Exception e){
    System.err.println(e);
    JOptionPane.showMessageDialog(null,e.getMessage());
}
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Membres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Membres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Membres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Membres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Membres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea comm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tble;
    private javax.swing.JTextField txtCARTE_FEDERALE;
    private javax.swing.JTextField txtCommentaires;
    private javax.swing.JTextField txtDATE_ATTESTATION;
    private javax.swing.JTextField txtDATE_ENTREE;
    private javax.swing.JTextField txtDATE_SEP;
    private javax.swing.JTextField txtDATE_VM;
    private javax.swing.JTextField txtLIEU_NAISSANCE;
    private javax.swing.JTextField txtMEMBRE_ACTIF;
    private javax.swing.JTextField txtMEMBRE_INSCRIT;
    private javax.swing.JTextField txtNUMERO_PPLA;
    private javax.swing.JTextField txtNUM_BADGE;
    private javax.swing.JTextField txtNUM_CIVILITE;
    private javax.swing.JTextField txtNUM_MEMBRE;
    private javax.swing.JTextField txtNUM_QUALIF;
    private javax.swing.JTextField txtVALIDITE_SEP;
    private javax.swing.JTextField txtVALIDITE_VM;
    private javax.swing.JTextField txtadresse;
    private javax.swing.JTextField txtcp;
    private javax.swing.JTextField txtdatenaiss;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtportable;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtprof;
    private javax.swing.JTextField txtre;
    private javax.swing.JTextField txtsolde;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txtville;
    // End of variables declaration//GEN-END:variables
}

